services:
  prisma-migrate:
    image: node:24-bookworm-slim
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
    command: npx prisma migrate deploy
    restart: "no"

  file-server:
    build:
      context: .
      dockerfile: Dockerfile.m
    image: file-server:latest
    container_name: file-server
    env_file:
      - .env
    ports:
      - "3002:3002"
    volumes:
      - /var/www/file-server-uploads:/uploads
    depends_on:
      - prisma-migrate
    restart: unless-stopped

    labels:
      - "traefik.enable=true"

      # 🔥 Disable request body buffering
      - "traefik.http.middlewares.no-buffer.buffering.maxRequestBodyBytes=0"
      - "traefik.http.middlewares.no-buffer.buffering.memRequestBodyBytes=0"

      # ✅ MUST match Dokploy service/router name
      - "traefik.http.routers.file-server-compose.middlewares=no-buffer"
