services:
  file-server:
    build:
      context: .
      dockerfile: Dockerfile.m
    image: file-server:latest
    container_name: file-server
    env_file:
      - .env
    ports:
      - "3002:3002"
    volumes:
      - /var/www/file-server-uploads:/app/uploads
    restart: unless-stopped
